run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - dogsled
    - dupl
    - errcheck
    - errname
    - exhaustive
    - godot
    - gosimple
    - gosec
    - govet
    - ineffassign
    - misspell
    - prealloc
    - predeclared
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck